name: 'GCP Auth'
description: 'Authenticates to Google Cloud using Workload Identity Federation.'
runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/472529661595/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions@preem-machine-ci.iam.gserviceaccount.com'
