import { Organization, RaceSeries, User } from './types';

export const users: User[] = [
  {
    id: 'eygr7FzGzsb987AVm5uavrYTP7Q2',
    name: 'Test User',
    email: 'test-user@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    role: 'contributor',
    organizationMemberships: [{ organizationId: 'org-1', role: 'member' }],
  },
  {
    id: 'user-1',
    name: 'Alex Doe',
    email: 'alex@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    role: 'contributor',
  },
  {
    id: 'user-2',
    name: 'Bike Race Inc. Admin',
    email: 'contact@bikerace.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    role: 'organizer',
    organizationMemberships: [{ organizationId: 'org-2', role: 'admin' }],
  },
  {
    id: 'user-3',
    name: 'Jane Smith',
    email: 'jane@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    role: 'contributor',
  },
  {
    id: 'user-4',
    name: 'Local Bike Shop',
    email: 'shop@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    role: 'contributor',
  },
  {
    id: 'user-5',
    name: 'Admin User',
    email: 'admin@preemmachine.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    role: 'admin',
  },
];

export const organizations: Organization[] = [
  {
    id: 'org-1',
    name: 'Super Sprinkles Racing',
  },
  {
    id: 'org-2',
    name: 'Bike Race Inc.',
  },
];

export const raceSeries: RaceSeries[] = [
  {
    id: 'series-1',
    organizationId: 'org-1',
    name: 'Il Giro di San Francisco',
    region: 'Northern California',
    website: 'https://girosf.com',
    startDate: '2025-09-01T00:00:00Z',
    endDate: '2025-09-01T00:00:00Z',
    events: [
      {
        id: 'event-1',
        seriesId: 'series-1',
        status: 'Upcoming',
        name: 'Il Giro di San Francisco',
        location: "Levi's Plaza, San Francisco",
        dateTime: '2025-09-01T08:00:00Z',
        races: [
          {
            id: 'race-1',
            eventId: 'event-1',
            status: 'Upcoming',
            name: 'Master Women 40+/50+',
            category: 'Masters',
            gender: 'Women',
            location: "Levi's Plaza, San Francisco",
            courseDetails: "Circuit race around Levi's Plaza.",
            maxRacers: 50,
            currentRacers: 0,
            ageCategory: '40+/50+',
            duration: '40 minutes',
            laps: 20,
            podiums: 3,
            sponsors: [],
            dateTime: '2025-09-01T08:00:00Z',
            preems: [
              {
                id: 'preem-1a',
                raceId: 'race-1',
                name: 'First Lap Leader',
                type: 'One-Shot',
                status: 'Awarded',
                prizePool: 100,
                sponsorInfo: { userId: 'user-4' },
                contributionHistory: [
                  {
                    id: 'c1',
                    contributorId: 'user-4',
                    amount: 100,
                    date: '2024-07-09T18:05:00Z',
                    message: 'Good luck racers!',
                  },
                ],
              },
              {
                id: 'preem-1b',
                raceId: 'race-1',
                name: 'Mid-Race Sprint',
                type: 'Pooled',
                status: 'Minimum Met',
                prizePool: 255,
                minimumThreshold: 200,
                timeLimit: '2024-07-09T19:30:00Z',
                sponsorInfo: null,
                contributionHistory: [
                  {
                    id: 'c2',
                    contributorId: 'user-1',
                    amount: 50,
                    date: '2024-07-09T18:10:00Z',
                  },
                  {
                    id: 'c3',
                    contributorId: 'user-3',
                    amount: 75,
                    date: '2024-07-09T18:12:00Z',
                    message: 'Lets go!',
                  },
                  {
                    id: 'c4',
                    contributorId: null,
                    amount: 30,
                    date: '2024-07-09T18:15:00Z',
                  },
                  {
                    id: 'c5',
                    contributorId: 'user-1',
                    amount: 100,
                    date: '2024-07-09T18:20:00Z',
                    message: 'Making it spicy!',
                  },
                ],
              },
              {
                id: 'preem-1c',
                raceId: 'race-1',
                name: 'Final Lap Leader',
                type: 'Pooled',
                status: 'Open',
                prizePool: 75,
                minimumThreshold: 150,
                sponsorInfo: null,
                contributionHistory: [
                  {
                    id: 'c6',
                    contributorId: 'user-3',
                    amount: 75,
                    date: '2024-07-09T18:25:00Z',
                  },
                ],
              },
            ],
          },
          {
            id: 'race-2',
            eventId: 'event-1',
            status: 'Upcoming',
            name: 'Junior 17-18 Championship',
            category: 'Juniors',
            gender: 'Open',
            location: "Levi's Plaza, San Francisco",
            courseDetails: "Circuit race around Levi's Plaza.",
            maxRacers: 50,
            currentRacers: 0,
            ageCategory: '17-18',
            duration: '40 minutes',
            laps: 20,
            podiums: 3,
            sponsors: [],
            dateTime: '2025-09-01T08:45:00Z',
            preems: [],
          },
        ],
      },
    ],
  },
  {
    id: 'series-2',
    organizationId: 'org-2',
    name: 'Chicago Grit',
    region: 'Chicagoland',
    website: 'https://chicago-grit.com/',
    startDate: '2026-07-17T00:00:00Z',
    endDate: '2026-07-26T00:00:00Z',
    events: [
      {
        id: 'event-2',
        seriesId: 'series-2',
        status: 'Upcoming',
        name: 'West Dundee',
        location: 'West Dundee, IL',
        dateTime: '2026-07-17T10:00:00Z',
        races: [
          {
            id: 'race-3',
            eventId: 'event-2',
            status: 'Upcoming',
            name: 'Pro/1/2 Men',
            category: 'Pro/1/2',
            gender: 'Men',
            location: 'West Dundee, IL',
            courseDetails: 'Challenging course with the "Leg Breaker Hill".',
            maxRacers: 100,
            currentRacers: 0,
            ageCategory: 'All Ages',
            duration: '60 minutes',
            laps: 30,
            podiums: 3,
            sponsors: [],
            dateTime: '2026-07-17T10:00:00Z',
            preems: [],
          },
          {
            id: 'race-4',
            eventId: 'event-2',
            status: 'Upcoming',
            name: 'Pro/1/2/3 Women',
            category: 'Pro/1/2/3',
            gender: 'Women',
            location: 'West Dundee, IL',
            courseDetails: 'Challenging course with the "Leg Breaker Hill".',
            maxRacers: 100,
            currentRacers: 0,
            ageCategory: 'All Ages',
            duration: '60 minutes',
            laps: 30,
            podiums: 3,
            sponsors: [],
            dateTime: '2026-07-17T11:00:00Z',
            preems: [],
          },
        ],
      },
      {
        id: 'event-3',
        seriesId: 'series-2',
        status: 'Upcoming',
        name: 'Lake Bluff',
        location: 'Lake Bluff, IL',
        dateTime: '2026-07-25T10:00:00Z',
        races: [
          {
            id: 'race-5',
            eventId: 'event-3',
            status: 'Upcoming',
            name: 'Pro/1/2 Men',
            category: 'Pro/1/2',
            gender: 'Men',
            location: 'Lake Bluff, IL',
            courseDetails: 'A technical course with a challenging chicane.',
            maxRacers: 100,
            currentRacers: 0,
            ageCategory: 'All Ages',
            duration: '60 minutes',
            laps: 30,
            podiums: 3,
            sponsors: [],
            dateTime: '2026-07-25T10:00:00Z',
            preems: [],
          },
          {
            id: 'race-6',
            eventId: 'event-3',
            status: 'Upcoming',
            name: 'Pro/1/2/3 Women',
            category: 'Pro/1/2/3',
            gender: 'Women',
            location: 'Lake Bluff, IL',
            courseDetails: 'A technical course with a challenging chicane.',
            maxRacers: 100,
            currentRacers: 0,
            ageCategory: 'All Ages',
            duration: '60 minutes',
            laps: 30,
            podiums: 3,
            sponsors: [],
            dateTime: '2026-07-25T11:00:00Z',
            preems: [],
          },
        ],
      },
      {
        id: 'event-4',
        seriesId: 'series-2',
        status: 'Upcoming',
        name: 'Fulton Market',
        location: 'Fulton Market, Chicago, IL',
        dateTime: '2026-07-26T10:00:00Z',
        races: [
          {
            id: 'race-7',
            eventId: 'event-4',
            status: 'Upcoming',
            name: 'Pro/1/2 Men',
            category: 'Pro/1/2',
            gender: 'Men',
            location: 'Fulton Market, Chicago, IL',
            courseDetails:
              "A new four-corner criterium that goes under the 'L' train tracks.",
            maxRacers: 100,
            currentRacers: 0,
            ageCategory: 'All Ages',
            duration: '75 minutes',
            laps: 40,
            podiums: 3,
            sponsors: [],
            dateTime: '2026-07-26T16:55:00Z',
            preems: [],
          },
          {
            id: 'race-8',
            eventId: 'event-4',
            status: 'Upcoming',
            name: 'Pro/1/2/3 Women',
            category: 'Pro/1/2/3',
            gender: 'Women',
            location: 'Fulton Market, Chicago, IL',
            courseDetails:
              "A new four-corner criterium that goes under the 'L' train tracks.",
            maxRacers: 100,
            currentRacers: 0,
            ageCategory: 'All Ages',
            duration: '75 minutes',
            laps: 40,
            podiums: 3,
            sponsors: [],
            dateTime: '2026-07-26T15:30:00Z',
            preems: [],
          },
        ],
      },
    ],
  },
];
