import { RaceSeries, User } from './types';

export const users: User[] = [
  {
    id: 'eygr7FzGzsb987AVm5uavrYTP7Q2',
    name: 'Test User',
    email: 'test-user@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    role: 'contributor',
  },
  {
    id: 'user-1',
    name: 'Alex Doe',
    email: 'alex@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    role: 'contributor',
  },
  {
    id: 'user-2',
    name: 'Bike Race Inc.',
    email: 'contact@bikerace.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    role: 'organizer',
  },
  {
    id: 'user-3',
    name: 'Jane Smith',
    email: 'jane@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    role: 'contributor',
  },
  {
    id: 'user-4',
    name: 'Local Bike Shop',
    email: 'shop@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    role: 'contributor',
  },
  {
    id: 'user-5',
    name: 'Admin User',
    email: 'admin@preemmachine.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    role: 'admin',
  },
];

export const raceSeries: RaceSeries[] = [
  {
    id: 'series-1',
    organizerId: 'user-2',
    name: 'Summer Criterium Series',
    region: 'Northern California',
    website: 'https://bikerace.com',
    startDate: '2024-07-01T00:00:00Z',
    endDate: '2024-09-30T00:00:00Z',
    races: [
      {
        id: 'race-1',
        seriesId: 'series-1',
        status: 'Live',
        name: 'Tuesday Night Crit',
        category: 'Cat 3/4',
        gender: 'Open',
        location: '100 Main St, Anytown, USA',
        courseDetails: 'A fast and flat 1.2 mile loop with 4 corners.',
        maxRacers: 75,
        currentRacers: 68,
        ageCategory: 'All Ages',
        duration: '60 minutes',
        laps: 30,
        podiums: 3,
        sponsors: ['Local Bike Shop', 'Coffee Stop'],
        dateTime: new Date(new Date().getTime() - 30 * 60 * 1000).toISOString(),
        preems: [
          {
            id: 'preem-1a',
            raceId: 'race-1',
            name: 'First Lap Leader',
            type: 'One-Shot',
            status: 'Awarded',
            prizePool: 100,
            sponsorInfo: { userId: 'user-4' },
            contributionHistory: [
              {
                id: 'c1',
                contributorId: 'user-4',
                amount: 100,
                date: '2024-07-09T18:05:00Z',
                message: 'Good luck racers!',
              },
            ],
          },
          {
            id: 'preem-1b',
            raceId: 'race-1',
            name: 'Mid-Race Sprint',
            type: 'Pooled',
            status: 'Minimum Met',
            prizePool: 255,
            minimumThreshold: 200,
            timeLimit: '2024-07-09T19:30:00Z',
            sponsorInfo: null,
            contributionHistory: [
              {
                id: 'c2',
                contributorId: 'user-1',
                amount: 50,
                date: '2024-07-09T18:10:00Z',
              },
              {
                id: 'c3',
                contributorId: 'user-3',
                amount: 75,
                date: '2024-07-09T18:12:00Z',
                message: 'Lets go!',
              },
              {
                id: 'c4',
                contributorId: null,
                amount: 30,
                date: '2024-07-09T18:15:00Z',
              },
              {
                id: 'c5',
                contributorId: 'user-1',
                amount: 100,
                date: '2024-07-09T18:20:00Z',
                message: 'Making it spicy!',
              },
            ],
          },
          {
            id: 'preem-1c',
            raceId: 'race-1',
            name: 'Final Lap Leader',
            type: 'Pooled',
            status: 'Open',
            prizePool: 75,
            minimumThreshold: 150,
            sponsorInfo: null,
            contributionHistory: [
              {
                id: 'c6',
                contributorId: 'user-3',
                amount: 75,
                date: '2024-07-09T18:25:00Z',
              },
            ],
          },
        ],
      },
      {
        id: 'race-2',
        seriesId: 'series-1',
        status: 'Upcoming',
        name: 'Weekend Road Race',
        category: 'Pro/1/2',
        gender: 'Women',
        location: '200 Mountain Rd, Hill Valley, USA',
        courseDetails:
          'A challenging 60-mile course with significant climbing.',
        maxRacers: 100,
        currentRacers: 45,
        ageCategory: 'All Ages',
        duration: 'Approx. 3 hours',
        laps: 3,
        podiums: 5,
        sponsors: ['Pro Cycling Team'],
        dateTime: new Date(
          new Date().getTime() + 7 * 24 * 60 * 60 * 1000
        ).toISOString(),
        preems: [],
      },
      {
        id: 'race-3',
        seriesId: 'series-1',
        status: 'Finished',
        name: 'Downtown Derby',
        category: 'Masters 40+',
        gender: 'Men',
        location: '300 City Park, Metroville, USA',
        courseDetails: 'Technical city circuit with tight corners.',
        maxRacers: 50,
        currentRacers: 50,
        ageCategory: 'Masters 40+',
        duration: '50 minutes',
        laps: 25,
        podiums: 3,
        sponsors: [],
        dateTime: new Date(
          new Date().getTime() - 7 * 24 * 60 * 60 * 1000
        ).toISOString(),
        preems: [
          {
            id: 'preem-3a',
            raceId: 'race-3',
            name: 'King of the Hill',
            type: 'Pooled',
            status: 'Awarded',
            prizePool: 500,
            sponsorInfo: null,
            contributionHistory: [],
          },
        ],
      },
    ],
  },
];
