# Config for the Gemini Pull Request Review Bot.
# https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github#configuration-schema

code_review:
  disable: false
  comment_severity_threshold: 'HIGH'
  max_review_comments: -1
  pull_request_opened:
    summary: false
