name: Auto Assign

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.pull_requests[0] }}
    steps:
      - name: 'Auto-assign PR'
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign.yml
