name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: ci
    env:
      AUTH_COOKIE_NAME: ${{ secrets.AUTH_COOKIE_NAME }}
      AUTH_COOKIE_SIGNATURE_KEY_CURRENT: ${{ secrets.AUTH_COOKIE_SIGNATURE_KEY_CURRENT }}
      AUTH_COOKIE_SIGNATURE_KEY_PREVIOUS: ${{ secrets.AUTH_COOKIE_SIGNATURE_KEY_PREVIOUS }}
      NEXT_PUBLIC_AUTH_DEBUG: ${{ secrets.NEXT_PUBLIC_AUTH_DEBUG }}
      NEXT_PUBLIC_DISABLE_HTTPS: ${{ secrets.NEXT_PUBLIC_DISABLE_HTTPS }}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_STRIPE_API_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_API_KEY }}
      SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_CLIENT_EMAIL }}
      SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      STRIPE_API_VERSION: ${{ secrets.STRIPE_API_VERSION }}
      FIRESTORE_EMULATOR_HOST: "localhost:8080"
      FIREBASE_AUTH_EMULATOR_HOST: "localhost:9099"

    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud.
      # Replace this with your own Nx Cloud token.
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"
      #   env:
      #     NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx playwright install --with-deps

      - name: Start Firebase emulators
        run: |
          npx firebase emulators:start --project=preem-machine-ci --only firestore,auth > firebase-emulator.log &
          timeout 60s grep -q "All emulators ready" <(tail -f firebase-emulator.log)

      # Run tests for affected projects. `nx affected` is more efficient than
      # `nx run-many` because it only runs tests for projects that have changed.
      - name: Run affected tests
        run: npx nx affected -t lint,test,e2e --parallel=3

      - name: Stop Firebase emulators
        if: always()
        run: |
          kill $(jobs -p) || true
