name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: ci
    env:
      AUTH_COOKIE_SIGNATURE_KEY_CURRENT: ${{ secrets.AUTH_COOKIE_SIGNATURE_KEY_CURRENT }}
      AUTH_COOKIE_SIGNATURE_KEY_PREVIOUS: ${{ secrets.AUTH_COOKIE_SIGNATURE_KEY_PREVIOUS }}
      DOTENV_SECRETS: ${{ secrets.DOTENV_SECRETS }}
      NEXT_PUBLIC_DEBUG_AUTH: ${{ secrets.NEXT_PUBLIC_DEBUG_AUTH }}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
      NEXT_PUBLIC_STRIPE_API_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_API_KEY }}
      NEXT_PUBLIC_USE_HTTPS: ${{ secrets.NEXT_PUBLIC_USE_HTTPS }}
      SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_CLIENT_EMAIL }}
      SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}

    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'

      - name: NPM CI
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npx nx --tuiAutoExit --outputStyle=static run-many -t build

      - name: Lint
        run: npx nx --tuiAutoExit --outputStyle=static run-many -t lint

      - name: Test
        run: npx nx --tuiAutoExit --outputStyle=static run-many -t test

      - name: E2E Deps
        run: npx playwright install --with-deps

      - name: E2E
        run: npx nx --tuiAutoExit --outputStyle=static run-many -t e2e

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/e2e-main/test-output/playwright/report
          retention-days: 30
